name: core ci

on:
  push:
    branches:
      - main
    paths:
      - 'packages/modern-di/**'
      - '.github/workflows/core-ci.yml'
  pull_request:
    paths:
      - 'packages/modern-di/**'
      - '.github/workflows/core-ci.yml'

concurrency:
  group: ${{ github.head_ref || github.run_id }} core
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: astral-sh/setup-uv@v3
      - run: uv python install 3.10
      - run: just install lint-ci

  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: astral-sh/setup-uv@v3
      - run: uv python install ${{ matrix.python-version }}
      - run: just install test
