name: Publish Package

on:
  release:
    types:
      - published

jobs:
  publish-core:
    if: startsWith(github.ref, 'core')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - run: just publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  publish-fastapi:
    if: startsWith(github.ref, 'fastapi')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: integrations/fastapi
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - run: just publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
