name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: astral-sh/setup-uv@v5
      - if: startsWith(github.ref_name, 'core')
        run: just publish modern-di
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

      - if: startsWith(github.ref_name, 'fastapi')
        run: just publish modern-di-fastapi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

      - if: startsWith(github.ref_name, 'litestar')
        run: just publish modern-di-litestar
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

      - if: startsWith(github.ref_name, 'faststream')
        run: just publish modern-di-faststream
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
