name: test core

on:
  push:
    branches:
      - main
    paths:
      - 'packages/modern-di/**'
      - '.github/workflows/test-core.yml'
  pull_request:
    paths:
      - 'packages/modern-di/**'
      - '.github/workflows/test-core.yml'

concurrency:
  group: ${{ github.head_ref || github.run_id }} core test
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: astral-sh/setup-uv@v5
      - run: uv python install ${{ matrix.python-version }}
      - run: |
          just install-ci modern-di
          just test-core
