name: test litestar

on:
  push:
    branches:
      - main
    paths:
      - 'packages/modern-di-litestar/**'
      - '.github/workflows/test-litestar.yml'
  pull_request:
    paths:
      - 'packages/modern-di-litestar/**'
      - '.github/workflows/test-litestar.yml'

concurrency:
  group: ${{ github.head_ref || github.run_id }} fastapi
  cancel-in-progress: false

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: astral-sh/setup-uv@v3
      - run: uv python install ${{ matrix.python-version }}
      - run: |
          just install-ci modern-di-litestar
          just test-litestar
